// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvl98Uwt-8yloxv6peJCB_SSeVsDGnmn0',
    appId: '1:1097356537457:android:7a8e05b3342a7ed90d35d0',
    messagingSenderId: '1097356537457',
    projectId: 'policyapp-e9a8b',
    storageBucket: 'policyapp-e9a8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5gcTFdqUJQnB0VYGMmG-phYnoIDxqbC4',
    appId: '1:1097356537457:ios:f76ea3901dfa073d0d35d0',
    messagingSenderId: '1097356537457',
    projectId: 'policyapp-e9a8b',
    storageBucket: 'policyapp-e9a8b.appspot.com',
    iosBundleId: 'com.example.privacyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6UMTtWEmtZkCqIk691rxg_yxdZ8fc5JA',
    appId: '1:1097356537457:web:e9f3707ccbde031e0d35d0',
    messagingSenderId: '1097356537457',
    projectId: 'policyapp-e9a8b',
    authDomain: 'policyapp-e9a8b.firebaseapp.com',
    storageBucket: 'policyapp-e9a8b.appspot.com',
    measurementId: 'G-RJ15QB0SLK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5gcTFdqUJQnB0VYGMmG-phYnoIDxqbC4',
    appId: '1:1097356537457:ios:f76ea3901dfa073d0d35d0',
    messagingSenderId: '1097356537457',
    projectId: 'policyapp-e9a8b',
    storageBucket: 'policyapp-e9a8b.appspot.com',
    iosBundleId: 'com.example.privacyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6UMTtWEmtZkCqIk691rxg_yxdZ8fc5JA',
    appId: '1:1097356537457:web:106f97df48980d9f0d35d0',
    messagingSenderId: '1097356537457',
    projectId: 'policyapp-e9a8b',
    authDomain: 'policyapp-e9a8b.firebaseapp.com',
    storageBucket: 'policyapp-e9a8b.appspot.com',
    measurementId: 'G-3ZNFWZN8ES',
  );

}